export const theme = {
    light: {
        colors: {
            primary: '#36693D',
            onPrimary: '#FFFFFF',
            primaryContainer: '#B8F1B9',
            onPrimaryContainer: '#1E5128',
            secondary: '#516350',
            onSecondary: '#FFFFFF',
            secondaryContainer: '#D4E8D0',
            onSecondaryContainer: '#3A4B3A',
            tertiary: '#39656C',
            onTertiary: '#FFFFFF',
            tertiaryContainer: '#BDEAF3',
            onTertiaryContainer: '#1F4D54',
            error: '#8A5023',
            onError: '#FFFFFF',
            errorContainer: '#FFDCC6',
            onErrorContainer: '#6E390D',
            surface: '#F7FBF2',
            onSurface: '#181D18',
            surfaceVariant: '#EBEFE7',
            onSurfaceVariant: '#424940',
            surfaceContainerLowest: '#FFFFFF',
            surfaceContainerLow: '#F1F5EC',
            surfaceContainerHigh: '#E5E9E1',
            surfaceContainerHighest: '#E0E4DB',
            outline: '#727970',
            outlineVariant: '#C1C9BE',
        }
    },
    dark: {
        colors: {
            primary: '#9DD49E',
            onPrimary: '#013913',
            primaryContainer: '#1E5128',
            onPrimaryContainer: '#B8F1B9',
            secondary: '#B8CCB5',
            onSecondary: '#243424',
            secondaryContainer: '#3A4B3A',
            onSecondaryContainer: '#D4E8D0',
            tertiary: '#A1CED6',
            onTertiary: '#00363D',
            tertiaryContainer: '#1F4D54',
            onTertiaryContainer: '#BDEAF3',
            error: '#FFB784',
            onError: '#4F2500',
            errorContainer: '#6D390C',
            onErrorContainer: '#FFDCC6',
            surface: '#101510',
            onSurface: '#E0E4DB',
            surfaceVariant: '#1C211C',
            onSurfaceVariant: '#C1C9BE',
            surfaceContainerLowest: '#0B0F0B',
            surfaceContainerLow: '#181D18',
            surfaceContainerHigh: '#272B26',
            surfaceContainerHighest: '#313630',
            outline: '#8C9389',
            outlineVariant: '#424940',
        }
    }
};